version: '3'

services:
  parser:
    build: .
    environment:
      - server_host=${server_host}
      - server_port=${server_port}
    command: python3 main.py ${server_host} ${server_port}
    restart: always